### ISSUE TITLE
Rechazado. 

### ISSUE THREAD

**Issue by t0kyolover** [4GeeksAcademy/ProyectoClase8DouglasM#1]
- [x] No crea nada en console.log
![Screenshot 2024-04-30 at 18 34 09](https://github.com/4GeeksAcademy/ProyectoClase8DouglasM/assets/144109471/887e3249-d588-4dbd-a607-b59bcb67e95e)

**Comment by MrDoux** [comment]
hola katya pero yo ejecuto node app.js en la terminal y lo genera 
![20240430_190754(651)](https://github.com/4GeeksAcademy/ProyectoClase8DouglasM/assets/160060653/1bb116d9-0512-448e-a031-8850e4193885)

**Comment by t0kyolover** [comment]
Perdona, me he confundido con el proyecto, tienes toda la razón.
